spring:
  application.name: genderinfilm

  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
#    liquibaseSchema:
#    defaultSchema:
